### ISSUE TITLE
Brew update fails with: Calling fails_with :llvm is deprecated

### ISSUE THREAD

**Issue by UNIVAC-Colonel-Panic** [prosody/homebrew-prosody#10]
Running on Mac OS X 10.7.5 (Lion)

It says to report it so I'm doing so. :-D This is a low priority issue for me.

```
Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/prosody/homebrew-prosody/prosody.rb:18:in '<class:Prosody>'
Please report this to the prosody/prosody tap!

Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/prosody/homebrew-prosody/prosody.rb:18:in '<class:Prosody>'
Please report this to the prosody/prosody tap!

Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/prosody/homebrew-prosody/prosody.rb:18:in '<class:Prosody>'
Please report this to the prosody/prosody tap!

Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/prosody/homebrew-prosody/prosody.rb:18:in '<class:Prosody>'
Please report this to the prosody/prosody tap!

```

**Comment by Zash** [comment]
This should have been fixed by #12
