### ISSUE TITLE
prosody 0.10.0

### ISSUE THREAD

**Issue by sonnyp** [prosody/homebrew-prosody#11]
Hey,

I'd like to send a PR for prosody 0.10.0, unfortunately I cannot get prosody to compile.

https://github.com/prosody/homebrew-prosody/compare/master...xmppjs:prosody-0.10.0?expand=1

```
⋊> ~/homebrew-prosody on prosody-0.10.0 ◦ brew install ./prosody.rb                                                                                                                                 19:41:16
Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/prosody/homebrew-prosody/prosody.rb:18:in `<class:Prosody>'
Please report this to the prosody/prosody tap!

Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/prosody/homebrew-prosody/prosody.rb:18:in `<class:Prosody>'
Please report this to the prosody/prosody tap!

Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/prosody/homebrew-prosody/prosody.rb:18:in `<class:Prosody>'
Please report this to the prosody/prosody tap!

Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/prosody/homebrew-prosody/prosody.rb:18:in `<class:Prosody>'
Please report this to the prosody/prosody tap!

==> Downloading https://prosody.im/downloads/source/prosody-0.10.0.tar.gz
Already downloaded: /Users/sonny/Library/Caches/Homebrew/prosody-0.10.0.tar.gz
==> ./configure --prefix=/usr/local/Cellar/prosody/0.10.0 --sysconfdir=/usr/local/etc/prosody --datadir=/usr/local/var/lib/prosody --with-lua=/usr/local/opt/lua@5.1 --with-lua-include=/usr/local/opt/lua@5
==> make
Last 15 lines from /Users/sonny/Library/Logs/Homebrew/prosody/02.make:
gcc -I/usr/local/opt/openssl/include -I/usr/local/opt/lua@5.1/include/lua5.1   -c -o pposix.o pposix.c
pposix.c:523:10: error: use of undeclared identifier 'RLIMIT_MEMLOCK'
                return RLIMIT_MEMLOCK;
                       ^
pposix.c:527:10: error: use of undeclared identifier 'RLIMIT_NPROC'
                return RLIMIT_NPROC;
                       ^
pposix.c:531:10: error: use of undeclared identifier 'RLIMIT_RSS'
                return RLIMIT_RSS;
                       ^
3 errors generated.
make[1]: *** [pposix.o] Error 1
make[1]: *** Waiting for unfinished jobs....
rm net.o encodings.o hashes.o
make: *** [all] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!
```

Any idea?

thanks

**Comment by Zash** [comment]
Hey, sorry about the slow response times here. We'll be updating to 0.9.14 here before switching to the 0.10 branch.

You could help by testing if this patch does the trick, or if you figured it out some other way.

``` diff
diff -r 7ec098b68042 util-src/pposix.c
--- a/util-src/pposix.c	Wed May 30 21:55:09 2018 +0100
+++ b/util-src/pposix.c	Thu May 31 19:36:05 2018 +0200
@@ -517,7 +517,7 @@ int string2resource(const char *s) {
 		return RLIMIT_STACK;
 	}
 
-#if !(defined(sun) || defined(__sun))
+#if !(defined(sun) || defined(__sun) || defined(__APPLE__))
 
 	if(!strcmp(s, "MEMLOCK")) {
 		return RLIMIT_MEMLOCK;
```

**Comment by Zash** [comment]
This should be fixed now, see https://issues.prosody.im/1202

Testing would be appreciated.
